### ISSUE TITLE
Release docker image for the CI

### ISSUE THREAD

**Issue by acc557** [simon987/sist2#118]
Could you release a docker image for the CI system that you use to build sist2?
https://github.com/simon987/sist2/blob/master/ci/build.sh seems to be missing a lot of context information about  compile-time dependencies installation.

**Comment by simon987** [comment]
Hi,
@acc557 are you having trouble compiling using the instructions in the readme? (https://github.com/simon987/sist2#build-from-source)

I'm using my fork of vcpkg in the CI build script because I sometimes cherry-pick patches and bug fixes before they get merged to master (especially for the arm64 builds) but it should work fine if you follow the instructions in the readme and use upstream vcpkg. Let me know if that is not the case.

Dockerfile
```
FROM ubuntu:16.04

MAINTAINER simon987 <me@simon987.net>

RUN apt  update
RUN apt install -y software-properties-common && add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN apt update && apt install -y gcc-7 g++-7 && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

RUN apt install -y git pkg-config python3 yasm ragel \
        automake autotools-dev wget libtool libssl-dev\
        curl zip unzip tar xorg-dev libglu1-mesa-dev libxcursor-dev\
        libxml2-dev libxinerama-dev\
        && apt clean

RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2.tar.gz && \
    tar -xzf cmake-*.tar.gz && cd cmake-* && ./bootstrap && make -j 12 && make install

RUN git clone --branch fix --depth 1  https://github.com/simon987/vcpkg.git  && cd vcpkg && ./bootstrap-vcpkg.sh && ./vcpkg integrate install
RUN ./vcpkg/vcpkg install curl[core,ssl]
RUN ./vcpkg/vcpkg install lmdb cjson glib brotli libarchive[core,bzip2,libxml2,lz4,lzma,lzo] pthread tesseract libxml2 ffmpeg libmupdf gtest mongoose libuuid libmagic libraw jasper lcms
```

**Comment by acc557** [comment]
Thank you for your reply.
However, the Dockerfile seem to fail when building bzip2. Here is the error message. Have you seen this before? 

```
Building package bzip2[core]:x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/db/db2ff046d4cc00e11b70690e506c4c4936a34050.zip
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: /vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:75 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:79 (include)
Error: Building package bzip2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-linux
  Vcpkg version: 2020.06.15-unknownhash
Additionally, attach any relevant sections from the log files above.
The command '/bin/sh -c ./vcpkg/vcpkg install lmdb cjson glib brotli libarchive[core,bzip2,libxml2,lz4,lzma,lzo] pthread tesseract libxml2 ffmpeg libmupdf gtest mongoose libuuid libmagic libraw jasper lcms' returned a non-zero code: 1
```

If you have not seen it before, I guess it's a problem on my side. I will try to rebuild and get `git-fetch-x64-linux-err.log` printed.

**Comment by acc557** [comment]
The error log contains `error: no such remote ref 75a94bea3918e612b879d6a11ca64b8689526147`

**Comment by simon987** [comment]
> Have you seen this before?

Yes, sorry I might have given you an outdated version of the Dockerfile. I'll try to find up-to-date version but I'm in the process of migrating all my file across systems, in the meantime IIRC the problem was that the `/vcpkg/downloads` folder wasn't automatically created, so you can try to add `&& mkdir /vcpkg/downloads` at the end of the `RUN git clone --branch fix ...`. If that still doesn't work you can also pull `simon987/ubuntu_ci`

**Comment by acc557** [comment]
Your docker image worked nicely. Thanks!
