### ISSUE TITLE
UTF-8 support for antiword

### ISSUE THREAD

**Issue by acc557** [simon987/sist2#146]
Antiword seems to work and generate thumb images, but it doesn't seem to convert the content .doc into UTF-8 which is required by Elasticsearch. Can it be run with antiword -m UTF-8 ?

https://www.freebsd.org/cgi/man.cgi?query=antiword&apropos=0&sektion=0&manpath=FreeBSD+6.3-RELEASE+and+Ports&format=html

**Comment by simon987** [comment]
Hi, could you attach an example of a .doc file that does not work with ES? Thanks

**Comment by acc557** [comment]
Could you try these?


[Downloads.zip](https://github.com/simon987/sist2/files/5800262/Downloads.zip)

**Comment by simon987** [comment]
I use the `-a` option to render the thumbnails, and antiword does not support UTF8 when exporting to PDFs so I have no way to  make the thumbnails work. I changed the code so that it will use the text-only version (which does support UTF8) to populate the `content` field so the text search should work for UTF-8, that's the best I can do without re-writing the entire thing from scratch

![image](https://user-images.githubusercontent.com/7120851/104818352-11131780-57f5-11eb-964d-2fedd2ea2a7e.png)
