### ISSUE TITLE
Feature Request - Add the links to the thumbnails.

### ISSUE THREAD

**Issue by UnR34L** [simon987/sist2#2]
Just a small thing, maybe I'm spoiled or lazy, but my brain tells me to click on the thumbnails to open a link on browsers.

Just something to consider.

**Comment by simon987** [comment]
The problem is that different file types will behave differently when clicked. For example, GIF images are automatically fetched on hover (or on tap, on mobile) and video images are be played on click.

What I could do is open the file on doubleclick, would that work? I want to avoid too many areas on the screen where you can accidentally open a link, especially on mobile

**Comment by UnR34L** [comment]
Yeah, after I posted the issue I thought, this wouldn't make sense for the video files.

Double clicking seems less intuitive, most people go in to single click mode on a browser, if that makes sense.

Could the white area inside the frame of a item be clickable? and possibly color change on hover? Seems easier for mobile users as well.

**Comment by simon987** [comment]
There's no such thing as hover on mobile, 
> Could the white area inside the frame of a item be clickable

Can you explain what you mean by that (with a screenshot, ideally), I'm not sure that I understand

**Comment by UnR34L** [comment]
I painted the area I was talking about in red. Making that a link just made sense to me.

![image](https://user-images.githubusercontent.com/5008396/68830352-51cc4980-06a3-11ea-82f6-d6f46e90e830.png)

When I said, easier for mobile users, I just ment, bigger surface area for them to click on.

**Comment by simon987** [comment]
Hi, sorry for the very long delay, I was debating how to do this without it being counter-intuitive. You should now be able to view the full-size image on click with version 1.2.11+
