### ISSUE TITLE
Incremental indexing, and removing entries from ES

### ISSUE THREAD

**Issue by yatli** [simon987/sist2#224]
I assume the scanner will maintain original vs. main every time an incremental scan is kicked off (old diff merged into original, then a new "main" created for new diff).

Currently, the indexer reads both main and original ndjson:

```c
    while ((de = readdir(dir)) != NULL) {
        if (strncmp(de->d_name, "_index_", sizeof("_index_") - 1) == 0) {
            char file_path[PATH_MAX];
            snprintf(file_path, PATH_MAX, "%s/%s", args->index_path, de->d_name);
            read_index(file_path, desc.id, desc.type, f);
            LOG_DEBUGF("main.c", "Read index file %s (%s)", file_path, desc.type)
        }
    }
```

Questions:

1. Is it okay to omit scanning the original one and only use "main"?
2. Can we update the scanner so that it keeps track of removed entries (create `_index_removed.ndjson.zst`), and during incremental index, send DELETE to the ES API.

**Comment by simon987** [comment]
Thank you for the suggestions

1. There used to be one _index_* file per thread, that's why there is a `while ((de = readdir(dir)) != NULL)` loop here. Right now I think it should only read the `_index_main.ndjson` file and the while loop should be removed.

2. That's a good idea

I will create separate issues for this.
