### ISSUE TITLE
QA: Workflow advice

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#31]
Hi

I am looking for some advice on the proper worfklow.

As of now I setup a cron job that removes existing index and then reindexes terabytes of data every 2days. This does not sound right to me because first the scanning and indexing takes many hours, then the database is 1.5 gb even though I am using the ``--fast` method. I can see some companies or people needing to make regular indexes and keep them as dated versions of search snapshots but that does not sound practical for daily use. 

I use Everything on Windows and these two apps are almost the same performance wise. However with Everything I do not have to erase the database, it does it transparently I guess.

I am looking for a way to come up with an efficient workflow that is easy on my system resources CPU, IO and storage wise. Is there a way to keep the  existing database and be more efficient with scan times and indexing? 

thanks

**Comment by simon987** [comment]
Hi, if you want to periodically update an index, you can use the `--incremental` flag, which will re-use an existing index and skip files that were not modified. 

This does not modify the original index so if you do not need it, you can safely delete it, and use the new index as the base for the next scan and so on (See  [scan options](https://github.com/simon987/sist2/blob/master/USAGE.md#scan-options).

Since you're using the `--fast` flag, you can use `--batch-size 10000` argument while `index`ing to speedup that step quite a bit.

As for the storage use, you can safely delete the `my_idx/_index_*` files as soon as the `index` step is done. (But if you do that, you can't use the `--incremental` flag).

If index size is a concern for you, I can open a new feature request to allow compressed indices, which should reduce the size by about 30%

**Comment by gerroon** [comment]
Hi

I am assuming that I need to make an actual index first to be able to run with incremental. Is it possible to make it so that it is smart enough to run an actual index if no index exists there? I would like this to be a single commandline if possible.

**Comment by simon987** [comment]
> Is it possible to make it so that it is smart enough to run an actual index if no index exists there?

That could be arranged. I'll try to make it happen in the next release

**Comment by simon987** [comment]
In the next release it will ignore the `--incremental` flag when the specified folder does not exist.

In-place update is not a feature I want to implement. You can run a periodical scan with a single index with something like this:
```
sist2 scan ~/files --incremental ./my_index/ -o /tmp/$(date +%Y_%m_%d) && rm -rf ./my_index/ && mv /tmp/$(date +%Y_%m_%d) ./my_index/
```

**Comment by gerroon** [comment]
Can the web server detect the updates of the new index while it is running? 

I understand that you d onot want to implement that type of update . My problem as a regular user is that that kind of indexing will keep adding new folders eveyr other day. Not sure how I can deal with that. Can it just delete the previous index? Or index sizes should not be a concern when incremental is in place.

**Comment by simon987** [comment]
> My problem as a regular user is that that kind of indexing will keep adding new folders eveyr other day Can it just delete the previous index?

Read the command, it does exactly that

> Can the web server detect the updates of the new index while it is running?

If you use incremental updates, it will probably work without having to restart the web server.

**Comment by dpieski** [comment]
Slightly off topic, but

> `sist2 scan ~/files --incremental ./my_index/ -o /tmp/$(date +%Y_%m_%d) && rm -rf ./my_index/ && mv /tmp/$(date +%Y_%m_%d) ./my_index/`

Just out of curiosity, would that "mv" command fail if the scan continues into another day? Or does the second $(date) get substituted before the third command is executed? jw since && requires the previous command to complete successfully. If the $(date) is only substituted once the command is triggered, couldn't it be the next day? 

Sorry for getting a little off topic.

**Comment by simon987** [comment]
I'm not sure, you'd have to test it

**Comment by yatli** [comment]
1. Use systemd timer to avoid re-triggering
2. Use a script variable to keep the filename: `DATE=$(date +%Y_%m_%d); sist2 scan .... -o /tmp/my_index_$DATE && ...`
