### ISSUE TITLE
Scan/Index: Error with mtime

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#373]
**Device Information (please complete the following information):**
 - OS: `[e.g., Ubuntu 20.04, WSL2]` Ubuntu 22.04
 - Deployment: `[Linux, Linux ARM64 or Docker]` Docker
 - Browser *(if relevant)*: `[e.g., chrome, safari]`
 - SIST2 Version: `[e.g., v2.9.0]` 3.1.2
 - Elasticsearch Version *(if relevant)* : `` 7.17.9

I am not sure whether this should be under Scan or Index. Maybe slightly both?

**Describe the bug**

During the `index` I get a few of these errors:
``` bash
2023-06-09 12:52:24 [ERROR elastic.c] {
	"index":	{
		"_index":	"sist2",
		"_type":	"_doc",
		"_id":	"03511db23821283e1cf5916e5f03fee7",
		"status":	400,
		"error":	{
			"type":	"mapper_parsing_exception",
			"reason":	"failed to parse field [mtime] of type [date] in document with id '03511db23821283e1cf5916e5f03fee7'. Preview of field's value: '-2147483648'",
			"caused_by":	{
				"type":	"illegal_argument_exception",
				"reason":	"failed to parse date field [-2147483648] with format [epoch_millis]",
				"caused_by":	{
					"type":	"date_time_parse_exception",
					"reason":	"Failed to parse with all enclosed parsers"
				}
			}
		}
	}
}
```

**Additional context**
I think this error relates to a number of files (~1200) that I have that have no date modified (which I also have someone looking into how this occurred). e.g.:
![image](https://github.com/simon987/sist2/assets/3300522/5e1dba59-cfbd-40e0-8a48-488271cc0ccd)

The doc is stored in the db with the negative mtime (shown below for the error above):

![image](https://github.com/simon987/sist2/assets/3300522/5901094a-4d09-4041-ab44-4d576d21cc78)

Bonus question:
When I get the Error from Elasticsearch, does the whole batch fail or just the single file with that error?

**Comment by simon987** [comment]
I restricted the `mtime` value to positive numbers, which should fix the problem.

**Comment by simon987** [comment]
> does the whole batch fail or just the single file with that error?

just the file(s) with the error

**Comment by overbyrn** [comment]
Could this change have anything to do with an issue I'm seeing on the latest pull whereby scan & index of a set of files works fine (using Elasticsearch as back-end), but in the sist2 Gui, the date picker has malformed dates.  Just ran a test of a new directory with files whose mtimes span multiple years.  Screenshots may explain it better.

Will open a fresh bug report if you'd prefer.

Incedentially, this only happens when using Elasticsearch as backend. No issues when using sqllite, dates look normal in picker.

![fig1](https://github.com/simon987/sist2/assets/545222/8591353d-8fd7-4e86-9591-d539b4d2c58e)
![fig2](https://github.com/simon987/sist2/assets/545222/1bc61e3a-b0aa-4f1e-8c08-4410eebf66b4)
![fig3](https://github.com/simon987/sist2/assets/545222/bb21a743-a14c-4d2b-92ad-33801b44eb0c)
