### ISSUE TITLE
Path filter picker does not show directories in order

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#55]
sist2 version: 2.3.2

(To investigate, see #54 )

**Comment by simon987** [comment]
![image](https://user-images.githubusercontent.com/7120851/83467364-b684a100-a447-11ea-9176-3213767f3b7b.png)

@dpieski I created a fictional directory tree and everything seem to be ordered alphabetically 

Could you send me a screenshot (or email me@simon987.net) of the unordered directories?

**Comment by dpieski** [comment]
Here is a (partial) screenshot from web 2.3.3
The folders seem to be return in order of subfile/subfolder quantity in parentheses at the end. If that is the case, your fictional directory tree would be ordered alphabetically because that may be a fall back for two folders with the same count?

In the below image, the first has (1495), the second has (1176) , the third have (779), etc.

![image](https://user-images.githubusercontent.com/3300522/83554163-f42e0c00-a4d1-11ea-997e-b71a81f0e76e.png)

**Comment by dpieski** [comment]
With `2.4.0` I no longer have this issue, all of the folders are in alphabetical order now.

**Comment by simon987** [comment]
Great! Thank you for checking
