### ISSUE TITLE
Does "--content-size 0" skip scanning content of files?

### ISSUE THREAD

**Issue by clb92** [simon987/sist2#8]
I'm looking for ways to speed up the scans. Indexing of content of files is not super important to me. Can I skip scanning of file content by doing "--content-size 0"? Or is there something else I missed?

**Comment by simon987** [comment]
> Can I skip scanning of file content by doing "--content-size 0"?

Yes, that's the intended behavior.
I just pushed a patch that will also skip loading pdf pages altogether if content-size is 0 (instead of loading only the first page). Will be effective after next release

But don't expect a significant speed boost, because the most expensive step in most cases is loading images and calculating thumbnails.

**Comment by clb92** [comment]
Thanks a lot!
Is there a way to tell it to skip thumbnails? If not, I'd really like that as an option too.

**Comment by simon987** [comment]
@clb92 When reading the code I realized that you need to set `--content-size` to a negative value to disable it, because `0` will use the default value

**Comment by clb92** [comment]
Thanks a lot for the heads-up!
